### ISSUE TITLE
Request: Un-minified source

### ISSUE THREAD

**Issue by vegeta897** [Aegis7Gaming/Discord-Invite-JS-HTML-CSS#1]
Thanks for publishing this repo, but I think it would be even better if you also included the source files before minification.

**Comment by Aegis7Gaming** [comment]
Done!

[[Reasons it wasn't de-minified to begin with]](https://www.reddit.com/r/discordapp/comments/7snjv9/like_the_discord_invite_box_get_the_code_to_use/dt6iic3/)

**Comment by Aegis7Gaming** [comment]
Resolved in #2
